# Generated by Django 5.2.7 on 2025-12-05 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospital", "0002_initial"),
        ("police_personnel", "0004_alter_personnel_area"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliationAVC09",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "insured_number",
                    models.CharField(max_length=128, verbose_name="insured number"),
                ),
                (
                    "employer_number",
                    models.CharField(max_length=128, verbose_name="employer number"),
                ),
                (
                    "type_risk",
                    models.CharField(max_length=255, verbose_name="type of risk"),
                ),
                ("isue_date", models.DateField(verbose_name="isue date")),
                ("from_date", models.DateField(verbose_name="from data")),
                ("to_date", models.DateField(verbose_name="until date")),
                (
                    "days_incapacity",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="days of disability"
                    ),
                ),
                (
                    "matricula",
                    models.CharField(max_length=128, verbose_name="insured number"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created At"
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modified At"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deleted At"
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hospital.hospital",
                        verbose_name="hospital",
                    ),
                ),
                (
                    "personnel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="police_personnel.personnel",
                        verbose_name="personel",
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliationavc09_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Created",
                    ),
                ),
                (
                    "user_deleted",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliationavc09_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Deleted",
                    ),
                ),
                (
                    "user_modified",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliationavc09_modified",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Modified",
                    ),
                ),
            ],
            options={
                "verbose_name": "Affiliation AVC09",
                "verbose_name_plural": "Affiliations AVC09",
                "db_table": "affiliationsavc09",
                "ordering": ["-created_at"],
            },
        ),
    ]
