# Generated by Django 5.2.7 on 2025-12-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliationavc09", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliationavc09",
            name="matricula",
            field=models.CharField(
                max_length=128, null=True, verbose_name="insured number"
            ),
        ),
    ]
