# Generated by Django 5.2.7 on 2025-12-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliationavc09", "0003_alter_affiliationavc09_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliationavc09",
            name="days_incapacity",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="days incapacity"
            ),
        ),
    ]
