# Generated by Django 5.2.7 on 2025-12-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliationavc09", "0004_alter_affiliationavc09_days_incapacity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliationavc09",
            name="from_date",
            field=models.DateField(verbose_name="from date"),
        ),
    ]
