# Generated by Django 5.2.7 on 2025-12-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("affiliationavc09", "0005_alter_affiliationavc09_from_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="affiliationavc09",
            name="delivery_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="delivery date"
            ),
        ),
        migrations.AddField(
            model_name="affiliationavc09",
            name="state",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="insured number"
            ),
        ),
    ]
