# Generated by Django 5.2.7 on 2025-11-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationAVC04',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='last name')),
                ('maternal_name', models.CharField(blank=True, max_length=128, verbose_name='maternal name')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='first name')),
                ('birthdate', models.DateField(verbose_name='birthdate')),
                ('genre', models.CharField(blank=True, max_length=20, verbose_name='genre')),
                ('joining_police', models.DateField(verbose_name='joining police')),
                ('insured_number', models.CharField(max_length=128, verbose_name='insured number')),
                ('company_name', models.CharField(max_length=128, verbose_name='company name')),
                ('employer_number', models.CharField(max_length=128, verbose_name='employer number')),
                ('current_destination', models.CharField(max_length=128, verbose_name='current destination')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('door_number', models.CharField(blank=True, max_length=10, verbose_name='door number')),
                ('area', models.CharField(max_length=100, verbose_name='area')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('salary', models.CharField(max_length=50, verbose_name='Salary')),
                ('occupation', models.CharField(max_length=100, verbose_name='Occupation')),
                ('date', models.DateField(verbose_name='Date')),
                ('extracted_text', models.TextField(blank=True)),
                ('extraction_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Affiliation AVC04',
                'verbose_name_plural': 'Affiliations AVC04',
                'db_table': 'affiliationsavc04',
                'ordering': ['-created_at'],
            },
        ),
    ]
