# Generated by Django 5.2.7 on 2025-11-21 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliationavc04', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliationavc04',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliationavc04_created', to=settings.AUTH_USER_MODEL, verbose_name='User Created'),
        ),
        migrations.AddField(
            model_name='affiliationavc04',
            name='user_deleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliationavc04_deleted', to=settings.AUTH_USER_MODEL, verbose_name='User Deleted'),
        ),
        migrations.AddField(
            model_name='affiliationavc04',
            name='user_modified',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliationavc04_modified', to=settings.AUTH_USER_MODEL, verbose_name='User Modified'),
        ),
    ]
