# Generated by Django 5.2.7 on 2025-11-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliationAVC07',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retirement_date', models.DateField(verbose_name='Retirement Date')),
                ('reason', models.CharField(max_length=100, verbose_name='Reason')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('salary', models.CharField(max_length=50, verbose_name='Salary')),
                ('occupation', models.CharField(max_length=100, verbose_name='Occupation')),
                ('date', models.DateField(verbose_name='Date')),
                ('status', models.IntegerField(default=1, verbose_name='Status')),
                ('document', models.FileField(blank=True, null=True, upload_to='affiliations/pdfs/', verbose_name='Document (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
            ],
            options={
                'verbose_name': 'Affiliation AVC07',
                'verbose_name_plural': 'Affiliations AVC07',
                'db_table': 'affiliationsavc07',
                'ordering': ['-created_at'],
            },
        ),
    ]
