# Generated by Django 5.2.7 on 2025-11-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliationavc07', '0001_initial'),
        ('police_personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliationavc07',
            name='personnel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affiliation_personnel', to='police_personnel.personnel', verbose_name='police personnel'),
        ),
    ]
