# Generated by Django 5.2.7 on 2025-11-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='last name')),
                ('maternal_name', models.CharField(blank=True, max_length=128, verbose_name='maternal name')),
                ('first_name', models.CharField(blank=True, max_length=128, verbose_name='first name')),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='middle name')),
                ('identity_card', models.CharField(max_length=20, null=True, unique=True, verbose_name='identity card')),
                ('birthdate', models.DateField(null=True, verbose_name='birthdate')),
                ('genre', models.CharField(blank=True, max_length=20, null=True, verbose_name='genre')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('joining_police', models.DateField(null=True, verbose_name='joining police')),
                ('scale', models.CharField(max_length=50, null=True, verbose_name='scale')),
                ('insured_number', models.CharField(max_length=128, null=True, verbose_name='insured number')),
                ('employer_number', models.CharField(max_length=128, null=True, verbose_name='employer number')),
                ('company_name', models.CharField(max_length=128, verbose_name='company name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('door_number', models.CharField(blank=True, max_length=10, verbose_name='door number')),
                ('area', models.CharField(max_length=100, verbose_name='area')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='reference')),
                ('reference_phone', models.CharField(blank=True, max_length=20, verbose_name='reference phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'police_personnel',
                'ordering': ['-created_at'],
            },
        ),
    ]
