# Generated by Django 5.2.7 on 2025-11-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        ('police_personnel', '0001_initial'),
        ('police_unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='current_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='police_unit.units', verbose_name='units'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='grades.grade', verbose_name='grade'),
        ),
    ]
