# Generated by Django 5.2.7 on 2025-12-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("police_personnel", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personnel",
            name="area",
            field=models.CharField(max_length=100, null=True, verbose_name="area"),
        ),
    ]
