# Generated by Django 5.2.7 on 2025-11-21 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('police_personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Unit Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('assistant', models.ManyToManyField(blank=True, null=True, related_name='assistant_units', to='police_personnel.personnel', verbose_name='Assistant')),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_unit', to='police_personnel.personnel', verbose_name='Commander')),
            ],
            options={
                'verbose_name': 'Police Unit',
                'verbose_name_plural': 'Police Units',
                'db_table': 'police_unit',
            },
        ),
    ]
