# Generated by Django 5.2.7 on 2025-11-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_personnel', '0003_initial'),
        ('police_unit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='assistant',
            field=models.ManyToManyField(blank=True, related_name='assistant_units', to='police_personnel.personnel', verbose_name='Assistant'),
        ),
    ]
