# Generated by Django 5.2.7 on 2025-11-26 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_personnel', '0003_initial'),
        ('police_unit', '0004_alter_units_commander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_unit', to='police_personnel.personnel', verbose_name='Commander'),
        ),
    ]
