# Generated by Django 5.2.7 on 2025-11-28 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("police_unit", "0005_alter_units_commander"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="units",
            name="user_updated",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policeunit_modified",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User Update",
            ),
        ),
    ]
