# Generated by Django 5.2.7 on 2025-11-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100, unique=True, verbose_name='grade')),
                ('grade_abbr', models.CharField(max_length=50, unique=True, verbose_name='grade abbreviation')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='deleted at')),
            ],
            options={
                'db_table': 'grade',
                'ordering': ['grade'],
            },
        ),
    ]
