# Generated by Django 5.2.7 on 2025-11-21 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='user_created',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_created', to=settings.AUTH_USER_MODEL, verbose_name='user created'),
        ),
        migrations.AddField(
            model_name='grade',
            name='user_deleted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_deleted', to=settings.AUTH_USER_MODEL, verbose_name='user deleted'),
        ),
        migrations.AddField(
            model_name='grade',
            name='user_updated',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_updated', to=settings.AUTH_USER_MODEL, verbose_name='user updated'),
        ),
    ]
