# Generated by Django 5.2.7 on 2025-12-08 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocMobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="avc09_uploads/", verbose_name="Documento subido"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(max_length=255, verbose_name="ID de Sesión WS"),
                ),
                (
                    "initial_points",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Puntos de corrección iniciales (JSON)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario de la sesión",
                    ),
                ),
            ],
            options={
                "verbose_name": "Afiliación AVC09",
                "verbose_name_plural": "Afiliaciones AVC09",
            },
        ),
    ]
