# Generated by Django 5.2.7 on 2025-11-28 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("police_personnel", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FilePersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "has_file",
                    models.BooleanField(default=False, verbose_name="has file"),
                ),
                (
                    "documents_has",
                    models.TextField(
                        blank=True, null=True, verbose_name="documents has"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="observation"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "personnel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_personnel",
                        to="police_personnel.personnel",
                        verbose_name="personnel",
                    ),
                ),
                (
                    "user_created",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Created",
                    ),
                ),
                (
                    "user_deleted",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Deleted",
                    ),
                ),
                (
                    "user_updated",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="file_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User Updated",
                    ),
                ),
            ],
            options={
                "db_table": "file_police",
                "ordering": ["-created_at"],
            },
        ),
    ]
