# Generated by Django 5.2.7 on 2025-11-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("file_personnel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="filepersonnel",
            table="file_personnel",
        ),
    ]
